%YAML:1.0
---
data:
  dataset_path: "../data/machine_hall/MH_01_easy"

pipeline:
  frontend:
    detector:
      type: fast
      threshold: 20
    selector:
      type: bucketer
      image_width: 752
      image_height: 480
      cell_width: 47 # 16 columns
      cell_height: 48 # 10 rows
      keypoints_per_cell: 5
